--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata: 
  name: ekscluster     
  region: ap-south-1
nodeGroups: 
- name: n1
  desiredCapacity: 2
  instanceType: t2.micro
  ssh: 
    publicKeyName: mykey2 
- name: ng2
  desiredCapacity: 1
  instanceType: t2.small
  ssh: 
    publicKeyName: mykey2
- name: ng3
  minSize: 1
  maxSize: 2
  instancesDistribution: 
    instanceTypes: ["t3.small", "t3.medium"]
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 50
    spotInstancePools: 2
  ssh: 
    publicKeyName: mykey2
